### ISSUE TITLE
Gestion de la Led Bleu

### ISSUE THREAD

**Issue by Miauto** [Miauto/Fi-DEL#2]
Pouvoir ce servir de la Led Bleu comme indicateur seulement et l'etteindre le reste du temp.
je connais pas les commandes dans arduino.

**Comment by hanklords** [comment]
Je pense que quelquechose dans le genre devrait marcher : la led bleue s'allume durant le setup et s'eteint à la fin.

``` c
int blueLedPin = 2;

void setup()
{
    pinMode(blueLedPin, OUTPUT);      // sets the digital pin as output
    digitalWrite(blueLedPin, HIGH);   // sets the LED on

    // Do setup

    digitalWrite(blueLedPin, LOW);   // sets the LED off
}
```

**Comment by Miauto** [comment]
Ça marche que pour les GPIO.
Hors cette led n'est pas citer dans les GPIO.
Je pense que la led doit pouvoir être attaqué depuis l'eeprom.

**Comment by Miauto** [comment]
je corrige.
ça marche si j'utilise pas le meme GPIO.
donc les led vont etre sur la D3=GPIO.0
merci @hanklords 

un simple   digitalWrite(2, HIGH); dans le setup suffit.

Attention c'est l'inverse
HIGH = Off
LOW = On
